
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__org_bluez_agent_interface_hpp__adaptor__H__
#define __sdbuscpp__org_bluez_agent_interface_hpp__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Agent1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Agent1";

protected:
    Agent1_adaptor(sdbus::IObject& object)
        : object_(&object)
    {
        object_->registerMethod("Release").onInterface(INTERFACE_NAME).implementedAs([this](){ return this->Release(); });
        object_->registerMethod("RequestPinCode").onInterface(INTERFACE_NAME).withInputParamNames("arg0").withOutputParamNames("arg0").implementedAs([this](const sdbus::ObjectPath& arg0){ return this->RequestPinCode(arg0); });
        object_->registerMethod("DisplayPinCode").onInterface(INTERFACE_NAME).withInputParamNames("arg0", "arg1").implementedAs([this](const sdbus::ObjectPath& arg0, const std::string& arg1){ return this->DisplayPinCode(arg0, arg1); });
        object_->registerMethod("RequestPasskey").onInterface(INTERFACE_NAME).withInputParamNames("arg0").withOutputParamNames("arg0").implementedAs([this](const sdbus::ObjectPath& arg0){ return this->RequestPasskey(arg0); });
        object_->registerMethod("DisplayPasskey").onInterface(INTERFACE_NAME).withInputParamNames("arg0", "arg1", "arg2").implementedAs([this](const sdbus::ObjectPath& arg0, const uint32_t& arg1, const uint16_t& arg2){ return this->DisplayPasskey(arg0, arg1, arg2); });
        object_->registerMethod("RequestConfirmation").onInterface(INTERFACE_NAME).withInputParamNames("arg0", "arg1").implementedAs([this](const sdbus::ObjectPath& arg0, const uint32_t& arg1){ return this->RequestConfirmation(arg0, arg1); });
        object_->registerMethod("RequestAuthorization").onInterface(INTERFACE_NAME).withInputParamNames("arg0").implementedAs([this](const sdbus::ObjectPath& arg0){ return this->RequestAuthorization(arg0); });
        object_->registerMethod("AuthorizeService").onInterface(INTERFACE_NAME).withInputParamNames("arg0", "arg1").implementedAs([this](const sdbus::ObjectPath& arg0, const std::string& arg1){ return this->AuthorizeService(arg0, arg1); });
        object_->registerMethod("Cancel").onInterface(INTERFACE_NAME).implementedAs([this](){ return this->Cancel(); });
    }

    Agent1_adaptor(const Agent1_adaptor&) = delete;
    Agent1_adaptor& operator=(const Agent1_adaptor&) = delete;
    Agent1_adaptor(Agent1_adaptor&&) = default;
    Agent1_adaptor& operator=(Agent1_adaptor&&) = default;

    ~Agent1_adaptor() = default;

private:
    virtual void Release() = 0;
    virtual std::string RequestPinCode(const sdbus::ObjectPath& arg0) = 0;
    virtual void DisplayPinCode(const sdbus::ObjectPath& arg0, const std::string& arg1) = 0;
    virtual uint32_t RequestPasskey(const sdbus::ObjectPath& arg0) = 0;
    virtual void DisplayPasskey(const sdbus::ObjectPath& arg0, const uint32_t& arg1, const uint16_t& arg2) = 0;
    virtual void RequestConfirmation(const sdbus::ObjectPath& arg0, const uint32_t& arg1) = 0;
    virtual void RequestAuthorization(const sdbus::ObjectPath& arg0) = 0;
    virtual void AuthorizeService(const sdbus::ObjectPath& arg0, const std::string& arg1) = 0;
    virtual void Cancel() = 0;

private:
    sdbus::IObject* object_;
};

}} // namespaces

#endif
