
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__org_bluez_proxy_hpp__proxy__H__
#define __sdbuscpp__org_bluez_proxy_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace freedesktop {
namespace DBus {

class Introspectable_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.Introspectable";

protected:
    Introspectable_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    Introspectable_proxy(const Introspectable_proxy&) = delete;
    Introspectable_proxy& operator=(const Introspectable_proxy&) = delete;
    Introspectable_proxy(Introspectable_proxy&&) = default;
    Introspectable_proxy& operator=(Introspectable_proxy&&) = default;

    ~Introspectable_proxy() = default;

public:
    std::string Introspect()
    {
        std::string result;
        proxy_->callMethod("Introspect").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

private:
    sdbus::IProxy* proxy_;
};

}}} // namespaces

namespace org {
namespace bluez {

class Adapter1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Adapter1";

protected:
    Adapter1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    Adapter1_proxy(const Adapter1_proxy&) = delete;
    Adapter1_proxy& operator=(const Adapter1_proxy&) = delete;
    Adapter1_proxy(Adapter1_proxy&&) = default;
    Adapter1_proxy& operator=(Adapter1_proxy&&) = default;

    ~Adapter1_proxy() = default;

public:
    void StartDiscovery()
    {
        proxy_->callMethod("StartDiscovery").onInterface(INTERFACE_NAME);
    }

    void SetDiscoveryFilter(const std::map<std::string, sdbus::Variant>& properties)
    {
        proxy_->callMethod("SetDiscoveryFilter").onInterface(INTERFACE_NAME).withArguments(properties);
    }

    void StopDiscovery()
    {
        proxy_->callMethod("StopDiscovery").onInterface(INTERFACE_NAME);
    }

    void RemoveDevice(const sdbus::ObjectPath& device)
    {
        proxy_->callMethod("RemoveDevice").onInterface(INTERFACE_NAME).withArguments(device);
    }

    std::vector<std::string> GetDiscoveryFilters()
    {
        std::vector<std::string> result;
        proxy_->callMethod("GetDiscoveryFilters").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

public:
    std::string Address()
    {
        return proxy_->getProperty("Address").onInterface(INTERFACE_NAME);
    }

    std::string AddressType()
    {
        return proxy_->getProperty("AddressType").onInterface(INTERFACE_NAME);
    }

    std::string Name()
    {
        return proxy_->getProperty("Name").onInterface(INTERFACE_NAME);
    }

    std::string Alias()
    {
        return proxy_->getProperty("Alias").onInterface(INTERFACE_NAME);
    }

    void Alias(const std::string& value)
    {
        proxy_->setProperty("Alias").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t Class()
    {
        return proxy_->getProperty("Class").onInterface(INTERFACE_NAME);
    }

    bool Powered()
    {
        return proxy_->getProperty("Powered").onInterface(INTERFACE_NAME);
    }

    void Powered(const bool& value)
    {
        proxy_->setProperty("Powered").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Discoverable()
    {
        return proxy_->getProperty("Discoverable").onInterface(INTERFACE_NAME);
    }

    void Discoverable(const bool& value)
    {
        proxy_->setProperty("Discoverable").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t DiscoverableTimeout()
    {
        return proxy_->getProperty("DiscoverableTimeout").onInterface(INTERFACE_NAME);
    }

    void DiscoverableTimeout(const uint32_t& value)
    {
        proxy_->setProperty("DiscoverableTimeout").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Pairable()
    {
        return proxy_->getProperty("Pairable").onInterface(INTERFACE_NAME);
    }

    void Pairable(const bool& value)
    {
        proxy_->setProperty("Pairable").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t PairableTimeout()
    {
        return proxy_->getProperty("PairableTimeout").onInterface(INTERFACE_NAME);
    }

    void PairableTimeout(const uint32_t& value)
    {
        proxy_->setProperty("PairableTimeout").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Discovering()
    {
        return proxy_->getProperty("Discovering").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> UUIDs()
    {
        return proxy_->getProperty("UUIDs").onInterface(INTERFACE_NAME);
    }

    std::string Modalias()
    {
        return proxy_->getProperty("Modalias").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> Roles()
    {
        return proxy_->getProperty("Roles").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> ExperimentalFeatures()
    {
        return proxy_->getProperty("ExperimentalFeatures").onInterface(INTERFACE_NAME);
    }

    uint16_t Manufacturer()
    {
        return proxy_->getProperty("Manufacturer").onInterface(INTERFACE_NAME);
    }

    uint8_t Version()
    {
        return proxy_->getProperty("Version").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace freedesktop {
namespace DBus {

class Properties_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.freedesktop.DBus.Properties";

protected:
    Properties_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
        proxy_->uponSignal("PropertiesChanged").onInterface(INTERFACE_NAME).call([this](const std::string& interface, const std::map<std::string, sdbus::Variant>& changed_properties, const std::vector<std::string>& invalidated_properties){ this->onPropertiesChanged(interface, changed_properties, invalidated_properties); });
    }

    Properties_proxy(const Properties_proxy&) = delete;
    Properties_proxy& operator=(const Properties_proxy&) = delete;
    Properties_proxy(Properties_proxy&&) = default;
    Properties_proxy& operator=(Properties_proxy&&) = default;

    ~Properties_proxy() = default;

    virtual void onPropertiesChanged(const std::string& interface, const std::map<std::string, sdbus::Variant>& changed_properties, const std::vector<std::string>& invalidated_properties) = 0;

public:
    sdbus::Variant Get(const std::string& interface, const std::string& name)
    {
        sdbus::Variant result;
        proxy_->callMethod("Get").onInterface(INTERFACE_NAME).withArguments(interface, name).storeResultsTo(result);
        return result;
    }

    void Set(const std::string& interface, const std::string& name, const sdbus::Variant& value)
    {
        proxy_->callMethod("Set").onInterface(INTERFACE_NAME).withArguments(interface, name, value);
    }

    std::map<std::string, sdbus::Variant> GetAll(const std::string& interface)
    {
        std::map<std::string, sdbus::Variant> result;
        proxy_->callMethod("GetAll").onInterface(INTERFACE_NAME).withArguments(interface).storeResultsTo(result);
        return result;
    }

private:
    sdbus::IProxy* proxy_;
};

}}} // namespaces

namespace org {
namespace bluez {

class BatteryProviderManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.BatteryProviderManager1";

protected:
    BatteryProviderManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    BatteryProviderManager1_proxy(const BatteryProviderManager1_proxy&) = delete;
    BatteryProviderManager1_proxy& operator=(const BatteryProviderManager1_proxy&) = delete;
    BatteryProviderManager1_proxy(BatteryProviderManager1_proxy&&) = default;
    BatteryProviderManager1_proxy& operator=(BatteryProviderManager1_proxy&&) = default;

    ~BatteryProviderManager1_proxy() = default;

public:
    void RegisterBatteryProvider(const sdbus::ObjectPath& provider)
    {
        proxy_->callMethod("RegisterBatteryProvider").onInterface(INTERFACE_NAME).withArguments(provider);
    }

    void UnregisterBatteryProvider(const sdbus::ObjectPath& provider)
    {
        proxy_->callMethod("UnregisterBatteryProvider").onInterface(INTERFACE_NAME).withArguments(provider);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class GattManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.GattManager1";

protected:
    GattManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    GattManager1_proxy(const GattManager1_proxy&) = delete;
    GattManager1_proxy& operator=(const GattManager1_proxy&) = delete;
    GattManager1_proxy(GattManager1_proxy&&) = default;
    GattManager1_proxy& operator=(GattManager1_proxy&&) = default;

    ~GattManager1_proxy() = default;

public:
    void RegisterApplication(const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options)
    {
        proxy_->callMethod("RegisterApplication").onInterface(INTERFACE_NAME).withArguments(application, options);
    }

    void UnregisterApplication(const sdbus::ObjectPath& application)
    {
        proxy_->callMethod("UnregisterApplication").onInterface(INTERFACE_NAME).withArguments(application);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class Media1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Media1";

protected:
    Media1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    Media1_proxy(const Media1_proxy&) = delete;
    Media1_proxy& operator=(const Media1_proxy&) = delete;
    Media1_proxy(Media1_proxy&&) = default;
    Media1_proxy& operator=(Media1_proxy&&) = default;

    ~Media1_proxy() = default;

public:
    void RegisterEndpoint(const sdbus::ObjectPath& endpoint, const std::map<std::string, sdbus::Variant>& properties)
    {
        proxy_->callMethod("RegisterEndpoint").onInterface(INTERFACE_NAME).withArguments(endpoint, properties);
    }

    void UnregisterEndpoint(const sdbus::ObjectPath& endpoint)
    {
        proxy_->callMethod("UnregisterEndpoint").onInterface(INTERFACE_NAME).withArguments(endpoint);
    }

    void RegisterPlayer(const sdbus::ObjectPath& player, const std::map<std::string, sdbus::Variant>& properties)
    {
        proxy_->callMethod("RegisterPlayer").onInterface(INTERFACE_NAME).withArguments(player, properties);
    }

    void UnregisterPlayer(const sdbus::ObjectPath& player)
    {
        proxy_->callMethod("UnregisterPlayer").onInterface(INTERFACE_NAME).withArguments(player);
    }

    void RegisterApplication(const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options)
    {
        proxy_->callMethod("RegisterApplication").onInterface(INTERFACE_NAME).withArguments(application, options);
    }

    void UnregisterApplication(const sdbus::ObjectPath& application)
    {
        proxy_->callMethod("UnregisterApplication").onInterface(INTERFACE_NAME).withArguments(application);
    }

public:
    std::vector<std::string> SupportedUUIDs()
    {
        return proxy_->getProperty("SupportedUUIDs").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class NetworkServer1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.NetworkServer1";

protected:
    NetworkServer1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    NetworkServer1_proxy(const NetworkServer1_proxy&) = delete;
    NetworkServer1_proxy& operator=(const NetworkServer1_proxy&) = delete;
    NetworkServer1_proxy(NetworkServer1_proxy&&) = default;
    NetworkServer1_proxy& operator=(NetworkServer1_proxy&&) = default;

    ~NetworkServer1_proxy() = default;

public:
    void Register(const std::string& uuid, const std::string& bridge)
    {
        proxy_->callMethod("Register").onInterface(INTERFACE_NAME).withArguments(uuid, bridge);
    }

    void Unregister(const std::string& uuid)
    {
        proxy_->callMethod("Unregister").onInterface(INTERFACE_NAME).withArguments(uuid);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class LEAdvertisingManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.LEAdvertisingManager1";

protected:
    LEAdvertisingManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    LEAdvertisingManager1_proxy(const LEAdvertisingManager1_proxy&) = delete;
    LEAdvertisingManager1_proxy& operator=(const LEAdvertisingManager1_proxy&) = delete;
    LEAdvertisingManager1_proxy(LEAdvertisingManager1_proxy&&) = default;
    LEAdvertisingManager1_proxy& operator=(LEAdvertisingManager1_proxy&&) = default;

    ~LEAdvertisingManager1_proxy() = default;

public:
    void RegisterAdvertisement(const sdbus::ObjectPath& advertisement, const std::map<std::string, sdbus::Variant>& options)
    {
        proxy_->callMethod("RegisterAdvertisement").onInterface(INTERFACE_NAME).withArguments(advertisement, options);
    }

    void UnregisterAdvertisement(const sdbus::ObjectPath& service)
    {
        proxy_->callMethod("UnregisterAdvertisement").onInterface(INTERFACE_NAME).withArguments(service);
    }

public:
    uint8_t ActiveInstances()
    {
        return proxy_->getProperty("ActiveInstances").onInterface(INTERFACE_NAME);
    }

    uint8_t SupportedInstances()
    {
        return proxy_->getProperty("SupportedInstances").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> SupportedIncludes()
    {
        return proxy_->getProperty("SupportedIncludes").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> SupportedSecondaryChannels()
    {
        return proxy_->getProperty("SupportedSecondaryChannels").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

#endif
