
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__org_bluez_agent_manager_proxy_hpp__proxy__H__
#define __sdbuscpp__org_bluez_agent_manager_proxy_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class AgentManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.AgentManager1";

protected:
    AgentManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    AgentManager1_proxy(const AgentManager1_proxy&) = delete;
    AgentManager1_proxy& operator=(const AgentManager1_proxy&) = delete;
    AgentManager1_proxy(AgentManager1_proxy&&) = default;
    AgentManager1_proxy& operator=(AgentManager1_proxy&&) = default;

    ~AgentManager1_proxy() = default;

public:
    void RegisterAgent(const sdbus::ObjectPath& agent, const std::string& capability)
    {
        proxy_->callMethod("RegisterAgent").onInterface(INTERFACE_NAME).withArguments(agent, capability);
    }

    void UnregisterAgent(const sdbus::ObjectPath& agent)
    {
        proxy_->callMethod("UnregisterAgent").onInterface(INTERFACE_NAME).withArguments(agent);
    }

    void RequestDefaultAgent(const sdbus::ObjectPath& agent)
    {
        proxy_->callMethod("RequestDefaultAgent").onInterface(INTERFACE_NAME).withArguments(agent);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class ProfileManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.ProfileManager1";

protected:
    ProfileManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    ProfileManager1_proxy(const ProfileManager1_proxy&) = delete;
    ProfileManager1_proxy& operator=(const ProfileManager1_proxy&) = delete;
    ProfileManager1_proxy(ProfileManager1_proxy&&) = default;
    ProfileManager1_proxy& operator=(ProfileManager1_proxy&&) = default;

    ~ProfileManager1_proxy() = default;

public:
    void RegisterProfile(const sdbus::ObjectPath& profile, const std::string& UUID, const std::map<std::string, sdbus::Variant>& options)
    {
        proxy_->callMethod("RegisterProfile").onInterface(INTERFACE_NAME).withArguments(profile, UUID, options);
    }

    void UnregisterProfile(const sdbus::ObjectPath& profile)
    {
        proxy_->callMethod("UnregisterProfile").onInterface(INTERFACE_NAME).withArguments(profile);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class HealthManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.HealthManager1";

protected:
    HealthManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    HealthManager1_proxy(const HealthManager1_proxy&) = delete;
    HealthManager1_proxy& operator=(const HealthManager1_proxy&) = delete;
    HealthManager1_proxy(HealthManager1_proxy&&) = default;
    HealthManager1_proxy& operator=(HealthManager1_proxy&&) = default;

    ~HealthManager1_proxy() = default;

public:
    sdbus::ObjectPath CreateApplication(const std::map<std::string, sdbus::Variant>& config)
    {
        sdbus::ObjectPath result;
        proxy_->callMethod("CreateApplication").onInterface(INTERFACE_NAME).withArguments(config).storeResultsTo(result);
        return result;
    }

    void DestroyApplication(const sdbus::ObjectPath& application)
    {
        proxy_->callMethod("DestroyApplication").onInterface(INTERFACE_NAME).withArguments(application);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

#endif
