
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp________include_Bluetooth__org_bluez_proxy_hpp__proxy__H__
#define __sdbuscpp________include_Bluetooth__org_bluez_proxy_hpp__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Adapter1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Adapter1";

protected:
    Adapter1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    Adapter1_proxy(const Adapter1_proxy&) = delete;
    Adapter1_proxy& operator=(const Adapter1_proxy&) = delete;
    Adapter1_proxy(Adapter1_proxy&&) = default;
    Adapter1_proxy& operator=(Adapter1_proxy&&) = default;

    ~Adapter1_proxy() = default;

public:
    void StartDiscovery()
    {
        proxy_->callMethod("StartDiscovery").onInterface(INTERFACE_NAME);
    }

    void StopDiscovery()
    {
        proxy_->callMethod("StopDiscovery").onInterface(INTERFACE_NAME);
    }

    void RemoveDevice(const sdbus::ObjectPath& device)
    {
        proxy_->callMethod("RemoveDevice").onInterface(INTERFACE_NAME).withArguments(device);
    }

    void SetDiscoveryFilter(const std::map<std::string, sdbus::Variant>& properties)
    {
        proxy_->callMethod("SetDiscoveryFilter").onInterface(INTERFACE_NAME).withArguments(properties);
    }

    std::vector<std::string> GetDiscoveryFilters()
    {
        std::vector<std::string> result;
        proxy_->callMethod("GetDiscoveryFilters").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

public:
    std::string Address()
    {
        return proxy_->getProperty("Address").onInterface(INTERFACE_NAME);
    }

    std::string AddressType()
    {
        return proxy_->getProperty("AddressType").onInterface(INTERFACE_NAME);
    }

    std::string Name()
    {
        return proxy_->getProperty("Name").onInterface(INTERFACE_NAME);
    }

    std::string Alias()
    {
        return proxy_->getProperty("Alias").onInterface(INTERFACE_NAME);
    }

    void Alias(const std::string& value)
    {
        proxy_->setProperty("Alias").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t Class()
    {
        return proxy_->getProperty("Class").onInterface(INTERFACE_NAME);
    }

    bool Powered()
    {
        return proxy_->getProperty("Powered").onInterface(INTERFACE_NAME);
    }

    void Powered(const bool& value)
    {
        proxy_->setProperty("Powered").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Discoverable()
    {
        return proxy_->getProperty("Discoverable").onInterface(INTERFACE_NAME);
    }

    void Discoverable(const bool& value)
    {
        proxy_->setProperty("Discoverable").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t DiscoverableTimeout()
    {
        return proxy_->getProperty("DiscoverableTimeout").onInterface(INTERFACE_NAME);
    }

    void DiscoverableTimeout(const uint32_t& value)
    {
        proxy_->setProperty("DiscoverableTimeout").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Pairable()
    {
        return proxy_->getProperty("Pairable").onInterface(INTERFACE_NAME);
    }

    void Pairable(const bool& value)
    {
        proxy_->setProperty("Pairable").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t PairableTimeout()
    {
        return proxy_->getProperty("PairableTimeout").onInterface(INTERFACE_NAME);
    }

    void PairableTimeout(const uint32_t& value)
    {
        proxy_->setProperty("PairableTimeout").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Discovering()
    {
        return proxy_->getProperty("Discovering").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> UUIDs()
    {
        return proxy_->getProperty("UUIDs").onInterface(INTERFACE_NAME);
    }

    std::string Modalias()
    {
        return proxy_->getProperty("Modalias").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> Roles()
    {
        return proxy_->getProperty("Roles").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class GattManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.GattManager1";

protected:
    GattManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    GattManager1_proxy(const GattManager1_proxy&) = delete;
    GattManager1_proxy& operator=(const GattManager1_proxy&) = delete;
    GattManager1_proxy(GattManager1_proxy&&) = default;
    GattManager1_proxy& operator=(GattManager1_proxy&&) = default;

    ~GattManager1_proxy() = default;

public:
    void RegisterApplication(const sdbus::ObjectPath& application, const std::map<std::string, sdbus::Variant>& options)
    {
        proxy_->callMethod("RegisterApplication").onInterface(INTERFACE_NAME).withArguments(application, options);
    }

    void UnregisterApplication(const sdbus::ObjectPath& application)
    {
        proxy_->callMethod("UnregisterApplication").onInterface(INTERFACE_NAME).withArguments(application);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class LEAdvertisingManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.LEAdvertisingManager1";

protected:
    LEAdvertisingManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    LEAdvertisingManager1_proxy(const LEAdvertisingManager1_proxy&) = delete;
    LEAdvertisingManager1_proxy& operator=(const LEAdvertisingManager1_proxy&) = delete;
    LEAdvertisingManager1_proxy(LEAdvertisingManager1_proxy&&) = default;
    LEAdvertisingManager1_proxy& operator=(LEAdvertisingManager1_proxy&&) = default;

    ~LEAdvertisingManager1_proxy() = default;

public:
    void RegisterAdvertisement(const sdbus::ObjectPath& advertisement, const std::map<std::string, sdbus::Variant>& options)
    {
        proxy_->callMethod("RegisterAdvertisement").onInterface(INTERFACE_NAME).withArguments(advertisement, options);
    }

    void UnregisterAdvertisement(const sdbus::ObjectPath& advertisement)
    {
        proxy_->callMethod("UnregisterAdvertisement").onInterface(INTERFACE_NAME).withArguments(advertisement);
    }

public:
    uint8_t ActiveInstances()
    {
        return proxy_->getProperty("ActiveInstances").onInterface(INTERFACE_NAME);
    }

    uint8_t SupportedInstances()
    {
        return proxy_->getProperty("SupportedInstances").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> SupportedIncludes()
    {
        return proxy_->getProperty("SupportedIncludes").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> SupportedSecondaryChannels()
    {
        return proxy_->getProperty("SupportedSecondaryChannels").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class AgentManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.AgentManager1";

protected:
    AgentManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    AgentManager1_proxy(const AgentManager1_proxy&) = delete;
    AgentManager1_proxy& operator=(const AgentManager1_proxy&) = delete;
    AgentManager1_proxy(AgentManager1_proxy&&) = default;
    AgentManager1_proxy& operator=(AgentManager1_proxy&&) = default;

    ~AgentManager1_proxy() = default;

public:
    void RegisterAgent(const sdbus::ObjectPath& agent, const std::string& capability)
    {
        proxy_->callMethod("RegisterAgent").onInterface(INTERFACE_NAME).withArguments(agent, capability);
    }

    void UnregisterAgent(const sdbus::ObjectPath& agent)
    {
        proxy_->callMethod("UnregisterAgent").onInterface(INTERFACE_NAME).withArguments(agent);
    }

    void RequestDefaultAgent(const sdbus::ObjectPath& agent)
    {
        proxy_->callMethod("RequestDefaultAgent").onInterface(INTERFACE_NAME).withArguments(agent);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

namespace org {
namespace bluez {

class Device1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Device1";

protected:
    Device1_proxy(sdbus::IProxy& proxy)
        : proxy_(&proxy)
    {
    }

    Device1_proxy(const Device1_proxy&) = delete;
    Device1_proxy& operator=(const Device1_proxy&) = delete;
    Device1_proxy(Device1_proxy&&) = default;
    Device1_proxy& operator=(Device1_proxy&&) = default;

    ~Device1_proxy() = default;

public:
    void Connect()
    {
        proxy_->callMethod("Connect").onInterface(INTERFACE_NAME);
    }

    void Disconnect()
    {
        proxy_->callMethod("Disconnect").onInterface(INTERFACE_NAME);
    }

    void ConnectProfile(const std::string& uuid)
    {
        proxy_->callMethod("ConnectProfile").onInterface(INTERFACE_NAME).withArguments(uuid);
    }

    void DisconnectProfile(const std::string& uuid)
    {
        proxy_->callMethod("DisconnectProfile").onInterface(INTERFACE_NAME).withArguments(uuid);
    }

    void Pair()
    {
        proxy_->callMethod("Pair").onInterface(INTERFACE_NAME);
    }

    void CancelPairing()
    {
        proxy_->callMethod("CancelPairing").onInterface(INTERFACE_NAME);
    }

public:
    std::string Address()
    {
        return proxy_->getProperty("Address").onInterface(INTERFACE_NAME);
    }

    std::string AddressType()
    {
        return proxy_->getProperty("AddressType").onInterface(INTERFACE_NAME);
    }

    std::string Name()
    {
        return proxy_->getProperty("Name").onInterface(INTERFACE_NAME);
    }

    std::string Alias()
    {
        return proxy_->getProperty("Alias").onInterface(INTERFACE_NAME);
    }

    void Alias(const std::string& value)
    {
        proxy_->setProperty("Alias").onInterface(INTERFACE_NAME).toValue(value);
    }

    uint32_t Class()
    {
        return proxy_->getProperty("Class").onInterface(INTERFACE_NAME);
    }

    uint16_t Appearance()
    {
        return proxy_->getProperty("Appearance").onInterface(INTERFACE_NAME);
    }

    std::string Icon()
    {
        return proxy_->getProperty("Icon").onInterface(INTERFACE_NAME);
    }

    bool Paired()
    {
        return proxy_->getProperty("Paired").onInterface(INTERFACE_NAME);
    }

    bool Trusted()
    {
        return proxy_->getProperty("Trusted").onInterface(INTERFACE_NAME);
    }

    void Trusted(const bool& value)
    {
        proxy_->setProperty("Trusted").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Blocked()
    {
        return proxy_->getProperty("Blocked").onInterface(INTERFACE_NAME);
    }

    void Blocked(const bool& value)
    {
        proxy_->setProperty("Blocked").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool LegacyPairing()
    {
        return proxy_->getProperty("LegacyPairing").onInterface(INTERFACE_NAME);
    }

    int16_t RSSI()
    {
        return proxy_->getProperty("RSSI").onInterface(INTERFACE_NAME);
    }

    bool Connected()
    {
        return proxy_->getProperty("Connected").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> UUIDs()
    {
        return proxy_->getProperty("UUIDs").onInterface(INTERFACE_NAME);
    }

    std::string Modalias()
    {
        return proxy_->getProperty("Modalias").onInterface(INTERFACE_NAME);
    }

    sdbus::ObjectPath Adapter()
    {
        return proxy_->getProperty("Adapter").onInterface(INTERFACE_NAME);
    }

    bool ServicesResolved()
    {
        return proxy_->getProperty("ServicesResolved").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy* proxy_;
};

}} // namespaces

#endif
