# Set install paths relative to ${CMAKE_INSTALL_PREFIX}

install(TARGETS ${PROJECT_EXEC_NAME} DESTINATION bin)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/ DESTINATION include/${PROJECT_NAME})
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/files/ DESTINATION files)
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/scripts/ DESTINATION bin)
install(TARGETS ${PROJECT_LIB_NAME}
	ARCHIVE DESTINATION lib		# Static Libraries
	LIBRARY DESTINATION lib		# Shared Libraries
)